[package]
name = "xb-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true
license = "GPL-2.0-or-later"

[features]
default = []
llvm = ["dep:inkwell"]

[dependencies]
thiserror.workspace = true
xb-frontend.workspace = true
inkwell = { workspace = true, optional = true }
