[package]
name = "xb-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true
license = "MIT"

[features]
default = []
llvm = ["dep:inkwell", "dep:libc"]

[dependencies]
thiserror.workspace = true
xb-frontend.workspace = true
inkwell = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
